author: Tuist
module: acho
github_url: https://github.com/tuist/acho
copyright: 'Copyright © from 2018 Pedro Piñera Buendía. All rights reserved.'
readme: ABOUT.md
sdk: macosx
min_acl: internal
xcodebuild_arguments:
  - -project
  - acho.xcodeproj
  - -scheme
  - acho-Package
skip_undocumented: true
